# Generated by Django 5.0.1 on 2024-01-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_manager_register',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
